apiVersion: apps/v1
kind: Deployment

metadata:
  name: smart-education-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: smart-education

  template:
    metadata:
      labels:
        app: smart-education

    spec:
      containers:
        - name: smart-education-analytics
          image: naresh110703/smart-education-analytics:latest
          imagePullPolicy: Always
          command: ["python", "src/main.py"]